### ISSUE TITLE
seit JS controller 2.1.0 keine Verbindung mehr

### ISSUE THREAD

**Issue by falke69** [ioBroker/MMM-ioBroker#4]
Hallo seit dem Update auf die Version 2.1.0 habe ich keine Verbindung mehr zum Iobroker.
Mir wird nur ein "-" anstatt der Inhalt der Systemvariable angezeigt.

`

          config: {

            host: '192.168.xxx.xxx',

            port: '8082',

            https: false,

      devices: [

          { name: 'offene Fenster:',

            deviceStates: [

                              { id: 'hm-rega.0.3102',},

 
`
Am Spiegel selbst habe ich keinerlei Veränderungen vorgenommen. Mit downgrade auf die letze stabile Version 1.5.14 läuft alles wieder wie früher. 

Gibt es hierfür vielleicht eine Lösung?

Danke

**Comment by volkerrichert** [comment]
Passiert das immer noch? Bei mir läuft 2.2.7 ohne große Probleme. Nur der reconnect scheint nicht zu gehen.

**Comment by falke69** [comment]
nein. Aktuell läuft alles wieder. :-)

**Comment by volkerrichert** [comment]
@falke69 Dann mach das doch bitte wieder zu. Es scheint ja gelöst zu sein
