### ISSUE TITLE
Only get a "undefined" message on the mirror

### ISSUE THREAD

**Issue by Masterg4941** [ioBroker/MMM-ioBroker#6]
Hi,

I tried about a few hours to get it work but I cant. It doesn´t matter what I change there is just a "undefined" message on the mirror. 
I tried to proof it with deconz Sensors and also with mqtt Sensors. Both are not working.
`{
			module: 'MMM-ioBroker',
			position: 'upper_third',
			config: {
				
					  host: '192.168.178.33',
					  port: '8082',
					  https: false,
					  template: 'MMM-ioBorker.njk',
					  devices: [
					  
								  { name: 'Test1',
									deviceStates: [
													  { id: 'mqtt.0.Temperatur_NodeMCU.Wetter.Temperature', icon: 'wi wi-thermometer', suffix: '&deg;' },
													  { id: 'deconz.0.Sensors.24.humidity',    icon: 'wi wi-humidity',    suffix: '%' }
												  ]
								  },
								  
								  
								  { name: 'writeHereTheName2',
									deviceStates: [
													  { id: 'deconz.0.Sensors.21.temperature', icon: 'wi wi-thermometer', suffix: '&deg;' },
													  { id: 'deconz.0.Sensors.24.humidity',    icon: 'wi wi-humidity',    suffix: '%' }
												  ]
								  }
								]
					}
		},
`

But if i take a API request (http://192.168.178.33:8087/get/deconz.0.Sensors.21.temperature) in the browser I receive an answer.

![Unbenannt](https://user-images.githubusercontent.com/59336833/73601088-10895e80-455b-11ea-9bf9-153d35f4f232.PNG)

Anyone an idea how I can fix this? 
![Unbenannt](https://user-images.githubusercontent.com/59336833/73601093-3a428580-455b-11ea-9b82-1a94a5a9ecf2.PNG)

**Comment by brummski** [comment]
Hi! look at your configuration, there is a typo in your template (it is wrong in the readme).
Had the same issue :)

m.

**Comment by Masterg4941** [comment]
Hi brummski,

which configuration do you mean? In the confog.js or the Iobroker?

**Comment by brummski** [comment]
config.js

look at 

`template: 'MMM-ioBorker.njk',`


ioBorker vs ioBroker :)

**Comment by Masterg4941** [comment]
Oh gosh *facepalm*
And I didn´t see it while trying for hours.
Now I get my values. Thank you!

**Comment by Masterg4941** [comment]
Oh gosh *facepalm*
And I didn´t see it while trying for hours.
Now I get my values. Thank you!
