### ISSUE TITLE
"undefined"

### ISSUE THREAD

**Issue by killstorme** [ioBroker/MMM-ioBroker#7]
"undefined" is displayed on my Magic Mirror. After installing MMM-ioBroker, I added the simple-api adapter in the iobroker. Now I can't get any further. I also set the host to 8081, 8082 and 8087 in Config.js, unfortunately this had no effect on the MM ,
I need help......

**Comment by oberpiller** [comment]
is it possible that you have added code from the readme into your config.js?
there is a typing error in it! 

`template: 'MMM-ioBorker.njk',`
is false.... it should be:
`template: 'MMM-ioBroker.njk',`

hope i could help you with that...

**Comment by killstorme** [comment]
yes, that was the mistake.
omg thank you oberpiller.
